[package]
name = "channels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.4"

[[bin]]
name = "channels"
# path = "src/main-basic.rs"
path = "src/main-two-way.rs"
